# Autogenerated wrapper script for IRL_jll for i686-w64-mingw32-cxx11
export libirl, libirl_c

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("IRL")
JLLWrappers.@declare_library_product(libirl, "libirl.dll")
JLLWrappers.@declare_library_product(libirl_c, "libirl_c.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libirl,
        "bin\\libirl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libirl_c,
        "bin\\libirl_c.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
